### ISSUE TITLE
run into type error using default constructor

### ISSUE THREAD

**Issue by chentc** [fluquid/find_job_titles#1]
>>> finder=Finder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fanglinchen/anaconda2/envs/py2Env/lib/python2.7/site-packages/find_job_titles/__init__.py", line 145, in __init__
    autom.add_word(title, title)
TypeError: string1 required

I can use the other constructor without a problem though!

**Comment by codinguncut** [comment]
very strange.
I'll look into this.
My main env is py3.5 so this might have to do with that, or with using anaconda...

**Comment by mcarolinag** [comment]
I have the same problem. I am using py3.7. Does it have to do StopIteration handling change in Python?

**Comment by codinguncut** [comment]
My apologies for my poor responsiveness, I am unfortunately caught up with a lot of other stuff.

Looks like an issue with "https://pyahocorasick.readthedocs.io/en/latest/#add-word-key-value-boolean", I wonder if the passed `title` might be empty or None...

I think `next()` for iterators may have changed in py3.7, and is now throwing `StopIteration` instead of returning `None`.

I have pushed a small change, but it doesn't relate to your issue, and I have been successfully passing the tests on linux using py3.7:

```
acora==2.2
alabaster==0.7.12
argh==0.26.2
asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
bleach==3.1.0
bumpversion==0.5.3
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
check-manifest==0.39
Click==7.0
coverage==4.5.4
cryptography==2.7
docutils==0.15.2
-e git+git@github.com:fluquid/find_job_titles.git@d4edfa77fd014b6d328ccc750ee78639de8883db#egg=find_job_titles
idna==2.8
imagesize==1.1.0
importlib-metadata==0.20
Jinja2==2.10.1
MarkupSafe==1.1.1
more-itertools==7.2.0
packaging==19.1
pathtools==0.1.2
pip-tools==4.1.0
pkginfo==1.5.0.1
pluggy==0.12.0
py==1.8.0
pyahocorasick==1.4.0
pycparser==2.19
Pygments==2.4.2
pyparsing==2.4.2
pytest==5.1.2
pytz==2019.2
PyYAML==5.1.2
readme-renderer==24.0
requests==2.22.0
requests-toolbelt==0.9.1
six==1.12.0
snowballstemmer==1.9.1
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
toml==0.10.0
tqdm==4.35.0
twine==1.13.0
urllib3==1.25.3
watchdog==0.9.0
wcwidth==0.1.7
webencodings==0.5.1
zipp==0.6.0
```

Let me know if I can help with this in any way.
